models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use app\behaviors\DateBehavior;
use Carbon\Carbon;
use DateTime;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $email
 * @property string $auth_key
 * @property string $name
 * @property string $surname
 * @property integer $gender
 * @property integer $status
 * @property string $created_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const GENDER_NOINFO = 0;
    const GENDER_MALE = 1;
    const GENDER_FEMALE = 2;

    public static $genderLabels = [
        'No info',
        'Male',
        'Female'
    ];

    public function behaviors()
    {
        return [

            'timestamp' => [

                'class' => DateBehavior::className(),

                'attributes' => [

                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', false],

                    ActiveRecord::EVENT_BEFORE_UPDATE => false,

                ],

            ],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    public function getTime()
    {
        return (Carbon::createFromFormat(DateTime::ISO8601, $this->created_at)->format('d-m-Y h:i'));
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username','name','surname','gender','email'],'required'],
            ['created_at','safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }
    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }
    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }
    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }
    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }
    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }
    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }
    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getPassword()
    {
        return '';
    }

    public function getAddress()
    {
        return $this->hasMany(Address::className(), ['id' => 'address_id'])
            ->viaTable('user_address', ['user_id' => 'id']);
    }
}

controllers/AddressController.php
<?php


namespace app\controllers;

use yii\web\Controller;
use app\models\Address;
use Yii;

class AddressController extends Controller
{
    public function actionAdd($userId = null)
    {
        $model = new Address();
        if ($model->load(Yii::$app->request->post()) && $userId = Yii::$app->request->post('userId')) {
            if ($model->saveWith($userId)) {
                return $this->goHome();
            }
        }
        return $this->render('add', ['model' => $model, 'userId' => $userId]);
    }

    public function actionUpdate($id)
    {
        $model = Address::findOne(['id' => $id]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->goBack();
        } else {
            return $this->render('update', ['model' => $model]);
        }
    }

    public function actionDelete($id)
    {
        $model = Address::findOne($id);

        if (Yii::$app->request->isPost) {
            if ($model->delete()) {
                Yii::$app->session->setFlash('success', 'Address deleted successfully');
            } else {
                Yii::$app->session->setFlash('error', 'Address can\'t be deleted');
            }
        }

        return $this->redirect(Yii::$app->request->referrer);
    }
}

controllers/UserController.php
<?php


namespace app\controllers;

use app\models\SignupForm;
use app\models\Address;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use Yii;
use yii\filters\AccessControl;

class UserController extends Controller
{
    /* public function behaviors()
     {
         return [
             'access' => [
                 'class' => AccessControl::className(),
                 'rules' => [
                     [
                         'allow' => true,
                         'actions' => ['update','delete'],
                         'roles' => ['@'],
                     ],
                 ],
             ],
         ];
     }*/

    public function actionAdd()
    {
        $model = new SignupForm();
        $address = new Address();
        if ($model->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post())) {
            if ($user = $model->signup($address)) {
                return $this->goHome();
            }
        }
        return $this->render('add', [
            'signupForm' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = User::findOne(['id' => $id]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->goHome();
        } else {
            return $this->render('update', ['model' => $model]);
        }
    }

    public function actionDelete($id)
    {
        $model = User::findOne($id);

        if (Yii::$app->request->isPost) {
            $model->unlinkAll('address', true);
            $model->delete();
            Yii::$app->session->setFlash('success', 'User deleted successfully');
        }

        return $this->goHome();
    }

    public function actionView($id)
    {
        $model = User::findOne(['id' => $id]);

        $addressProvider = new ActiveDataProvider([
            'query' => $model->getAddress(),
            'pagination' => [
                'pageSize' => 5
            ]
        ]);

        return $this->render('view', ['user' => $model, 'addressProvider' => $addressProvider]);
    }

    public function actionList()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find()
        ]);

        return $this->render('list', [
            'dataProvider' => $dataProvider
        ]);
    }
}

views/user/_userForm.php
<?php
use app\models\User;

?>

<?= $form->field($user, 'username')->textInput() ?>
<?= $form->field($user, 'name')->textInput() ?>
<?= $form->field($user, 'surname')->textInput() ?>
<?= $form->field($user, 'password')->passwordInput() ?>
<?= $form->field($user, 'gender')->dropDownList(
    [User::GENDER_NOINFO => 'No info', User::GENDER_MALE => 'Male', User::GENDER_FEMALE => 'Female']
); ?>
<?= $form->field($user, 'email')->input('email');

views/user/add.php
<?php
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use app\models\Address;
use Yii;

$form = ActiveForm::begin(['method' => 'post']);
?>
<?= Yii::$app->controller->renderPartial('_userForm', ['user' => $signupForm, 'form' => $form]) ?>

<?=
$this->renderFile(
    __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'address'.DIRECTORY_SEPARATOR.'_addressForm.php',
    ['address' => new Address(), 'form' => $form]
)
?>

<div class="form-group">
    <?= Html::submitButton('Add user', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
</div>


<?php
ActiveForm::end();
?>

views/user/list.php
<?php
use app\models\User;
use yii\grid\GridView;

$columns = [
    'username',
    'email',
    'name',
    'surname',
    [
        'attribute' => 'gender',
        'value' => function ($model) {
            return User::$genderLabels[$model->gender];
        }
    ],
    'time',
    [
        'class' => 'yii\grid\ActionColumn',
        'template' =>  Yii::$app->user->isGuest ? '{view}' : '{update} {delete}',
    ]
];

?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $columns
]);

views/user/update.php
<?php
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use app\models\Address;
use Yii;

$form = ActiveForm::begin(['method' => 'post']);
?>

<?= Yii::$app->controller->renderPartial('_userForm', ['user' => $model, 'form' => $form]) ?>

<div class="form-group">
    <?= Html::submitButton('Update user', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
</div>


<?php
ActiveForm::end();
?>

views/user/view.php
<?php
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\models\User;
use yii\bootstrap\Html;
?>

<?= DetailView::widget([
    'model' => $user,
    'attributes' => [
        'username',
        'email',
        'name',
        'surname',
        [
            'attribute' => 'gender',
            'value' => function ($model) {
                return User::$genderLabels[$model->gender];
            }
        ],
        'time'
    ]
]); ?>

<br/>
<?= Html::a('Create address', ['address/add','userId' => $user->id], ['class' => 'btn btn-success']) ?>
<hr/>

<?= GridView::widget([
    'dataProvider' => $addressProvider,
    'columns' => [
        'post_index',
        'country',
        'city',
        'street',
        'house',
        'apartment',
        [
            'class' => 'yii\grid\ActionColumn',
            'controller' => 'address',
            'template' =>  '{update} {delete}',
        ]
    ]
]); ?>